name: ratul_er
description: "A personal portfolio made by Flutter"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  responsive_framework: ^1.5.1
  shimmer: ^3.0.0
  animations: ^2.0.11
  

  #Firebase
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  cloud_firestore: ^5.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
